services:
    nfq_soap.data_collector:
        class: Nfq\Bundle\SoapBundle\DataCollector\SoapDataCollector
        tags:
            - { name: data_collector, template: '@NfqSoap/Collector/soap.html.twig', id: 'nfq_soap' }
            - { name: kernel.event_listener, event: nfq_soap.request_finished, method: onRequestFinished }

    nfq_soap.factory:
        class: Nfq\Bundle\SoapBundle\Factory
        arguments: ["@event_dispatcher"]

    pretty_xml.formatter:
        class: PrettyXml\Formatter
        public: false

    pretty_xml.formatter.twig_extension:
        class: Nfq\Bundle\SoapBundle\Twig\FormatterExtension
        arguments:
            - "@pretty_xml.formatter"
        public: false
        tags:
            - { name: twig.extension }
