language: php

cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - 7.1
  - 7.2

matrix:
  fast_finish: true
  include:
    # Test against Symfony LTS versions
    - php: 7.1
      env: SYMFONY_VERSION="4.1.*"
    - php: 7.2
      env: SYMFONY_VERSION="4.1.*"
    # Test against dev versions
    - php: 7.1
      env: DEPENDENCIES=dev
    - php: 7.2
      env: DEPENDENCIES=dev
  allow_failures:
    - env: DEPENDENCIES=dev

before_install:
  - composer self-update
  - if [ "$DEPENDENCIES" = "dev" ]; then perl -pi -e 's/^}$/,"minimum-stability":"dev"}/' composer.json; fi;
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update symfony/symfony:"$SYMFONY_VERSION"; fi

install:
    - composer update $COMPOSER_FLAGS

script: vendor/bin/phpunit -v --coverage-text
